# Site Settings
title: GPTales
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of diverse stories written by AI.
baseurl: '/GPTales' # the subpath of your site, e.g. /blog
url: 'https://tm-lbenson.github.io' # the base hostname & protocol for your site
github_username: tm-lbenson

# Build Settings
markdown: kramdown
theme: minima
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
